// Complete Bilingual Dictionary (Hindi & English) for Yug Finance Manager 2.0

export type SupportedLanguage = 'hi' | 'en';

export const DICTIONARY: Record<SupportedLanguage, Record<string, string>> = {
  hi: {
    // Navigation & App
    appName: 'युग फाइनेंस २.०',
    tagline: '१००% ऑफलाइन व्यक्तिगत और घरेलू वित्त प्रबंधक',
    dashboard: 'डैशबोर्ड',
    money: 'पैसे',
    household: 'घरेलू खर्च',
    inventory: 'इन्वेंटरी',
    goals: 'लक्ष्य (Goals)',
    budget: 'बजट',
    recurring: 'आवर्ती (Recurring)',
    reports: 'रिपोर्ट्स',
    more: 'अधिक / सेटिंग्स',
    settings: 'सेटिंग्स',
    search: 'खोजें (Search)',

    // Info & Sidebar
    aboutUs: 'हमारे बारे में (About Us)',
    privacyPolicy: 'गोपनीयता नीति (Privacy Policy)',
    disclaimer: 'अस्वीकरण (Disclaimer)',
    termsOfUse: 'उपयोग की शर्तें (Terms)',
    contactSupport: 'सहायता / संपर्क',
    quickActions: 'त्वरित कार्य (Quick Actions)',
    modules: 'मॉड्यूल चालू/बंद',

    // Dashboard Metrics
    netWorth: 'कुल संपत्ति (Net Worth)',
    availableMoney: 'उपलब्ध नकदी (Available Money)',
    previousBalance: 'पिछला शेष',
    startOfMonth: 'महीने की शुरुआत',
    totalIncome: 'कुल आय (Income)',
    thisMonth: 'इस महीने',
    totalExpense: 'कुल व्यय (Expense)',
    monthlyNetChange: 'मासिक शुद्ध परिवर्तन',
    netBalance: 'शुद्ध शेष (Balance)',
    available: 'उपलब्ध',
    savingsRate: 'बचत दर (Savings Rate)',
    totalLend: 'कुल दिया उधार (Lend)',
    remainingPrincipal: 'शेष मूलधन',
    totalInvested: 'कुल निवेश (Invested)',
    currentValue: 'वर्तमान मूल्य',
    totalDebt: 'कुल लिया उधार/कर्ज (Debt)',
    activeDebts: 'सक्रिय देनदारी (Liability)',
    cashBalance: 'नकद शेष (Cash)',
    bankBalance: 'बैंक शेष (Bank)',
    recentActivities: 'हाल की गतिविधियां',
    noRecentActivities: 'कोई हालिया गतिविधि नहीं।',
    checkAccountBalances: 'खाता शेष राशि जांचें',

    // Quick Add Buttons
    addIncome: '+ आय जोड़ें',
    addExpense: '- खर्च जोड़ें',
    transfer: 'हस्तांतरण (Transfer)',
    addLend: 'उधार दें (Lend)',
    addBorrow: 'कर्ज लें (Borrow)',
    addInvestment: 'निवेश करें (Invest)',
    addGrocery: 'किराना (Grocery)',
    addMilk: 'दूध (Milk)',
    addWater: 'पानी (Water)',
    addGoal: 'नया लक्ष्य (Goal)',
    quickAdd: 'नया जोड़ें (Quick Add)',

    // Money Module
    income: 'आय',
    expense: 'व्यय',
    cash: 'नकद',
    bankAccounts: 'बैंक खाते',
    lend: 'उधार (Lend)',
    borrow: 'कर्ज / देनदारी (Borrow)',
    investments: 'निवेश (Investments)',
    transfers: 'हस्तांतरण',
    newTransaction: 'नया लेनदेन',
    editTransaction: 'लेनदेन संपादित करें',
    amount: 'राशि (₹)',
    date: 'तिथि',
    category: 'श्रेणी (Category)',
    account: 'खाता (Account)',
    description: 'विवरण',
    note: 'नोट / टिप्पणी',
    fromAccount: 'इस खाते से (From)',
    toAccount: 'इस खाते में (To)',
    saveTransaction: 'लेनदेन सहेजें',

    // Bank Account Manager
    addAccount: 'नया खाता जोड़ें',
    editAccount: 'खाता संपादित करें',
    accountName: 'खाते का नाम',
    accountType: 'खाते का प्रकार',
    openingBalance: 'शुरुआती शेष (Opening Balance)',
    currentBalance: 'वर्तमान शेष',
    accountSavings: 'बचत खाता (Savings)',
    accountCurrent: 'चालू खाता (Current)',
    accountCash: 'नकद (Cash)',
    accountWallet: 'वॉलेट (Wallet)',
    accountOther: 'अन्य (Other)',
    saveAccount: 'खाता सहेजें',
    accountDeleted: 'खाता हटा दिया गया',
    cannotDeleteAccountWithTx: 'इस खाते में लेनदेन जुड़े हैं, इसे हटाया नहीं जा सकता!',

    // Lend Module
    lendSection: 'उधार देना (Lend Manager)',
    activeLoans: 'सक्रिय ऋण (Active Loans)',
    closedLoans: 'बंद ऋण (Closed Loans)',
    noActiveLend: 'कोई सक्रिय उधार नहीं।',
    noClosedLend: 'कोई बंद उधार नहीं।',
    personName: 'व्यक्ति का नाम',
    amountGiven: 'दी गई राशि (₹)',
    amountReceived: 'प्राप्त राशि (₹)',
    remainingAmount: 'शेष राशि',
    interestRate: 'ब्याज दर (% प्रति वर्ष)',
    emiTerm: 'ईएमआई अवधि (महीने)',
    returnDate: 'अंतिम वापसी तिथि',
    addRepayment: 'भुगतान प्राप्त करें (Repayment)',
    addMoreLoan: 'और राशि दें (Add Principal)',
    loanHistory: 'लोन इतिहास (History)',
    markAsCompleted: 'ऋण बंद करें (Mark Closed)',
    markAsActive: 'सक्रिय करें (Reopen)',

    // Borrow / Debt Module
    debtSection: 'लिया गया कर्ज / देनदारी (Debt & Borrow)',
    activeDebtsList: 'सक्रिय देनदारियां',
    closedDebtsList: 'चुकाई गई देनदारियां',
    noActiveDebt: 'कोई सक्रिय देनदारी नहीं।',
    noClosedDebt: 'कोई बंद देनदारी नहीं।',
    borrowFrom: 'किससे उधार लिया (Person/Bank)',
    amountBorrowed: 'उधार ली गई राशि (₹)',
    paidAmount: 'चुकाई गई राशि (₹)',
    dueDate: 'देय तिथि (Due Date)',
    payDebt: 'कर्ज चुकाएं (Repay)',
    debtRepayment: 'कर्ज वापसी प्रविष्टि',

    // Investment Module
    investSection: 'निवेश पोर्टफोलियो (Investments)',
    activePortfolios: 'सक्रिय पोर्टफोलियो',
    closedPortfolios: 'बंद पोर्टफोलियो',
    noActiveInvestments: 'कोई सक्रिय निवेश नहीं।',
    portfolioName: 'पोर्टफोलियो का नाम',
    investmentType: 'निवेश प्रकार',
    investedAmount: 'कुल निवेश राशि',
    withdrawnAmount: 'निकाली गई राशि',
    netInvested: 'नेट निवेश',
    withdrawAmount: 'रकम निकालें (Withdraw)',
    updateCurrentValue: 'वर्तमान मूल्य अपडेट करें (Manual)',
    manualValuationNotice: 'बाज़ार मूल्य केवल आपके द्वारा मैन्युअल रूप से अपडेट किया जाता है (100% ऑफलाइन)।',

    // Household Module
    householdSection: 'घरेलू खर्च प्रबंधक (Household)',
    todayHousehold: 'आज का घरेलू खर्च',
    monthlyHousehold: 'इस महीने का घरेलू खर्च',
    grocery: 'किराना (Grocery)',
    milk: 'दूध (Milk)',
    water: 'पानी (Water)',
    vegetables: 'सब्जियां (Vegetables)',
    fruits: 'फल (Fruits)',
    meat: 'मीट (Meat)',
    fish: 'मछली (Fish)',
    food: 'भोजन/नाश्ता (Food)',
    fuel: 'ईंधन / पेट्रोल (Fuel)',
    medicine: 'दवाइयां (Medicine)',
    bills: 'बिल व उपयोगिता (Bills)',
    shopping: 'खरीदारी (Shopping)',
    otherHousehold: 'अन्य घरेलू',

    // Grocery & Milk & Water specific
    itemName: 'वस्तु का नाम (Item)',
    quantity: 'मात्रा (Quantity)',
    unit: 'इकाई (Unit)',
    ratePerUnit: 'दर (Rate per Unit ₹)',
    shopVendor: 'दुकानदार / विक्रेता',
    dailyCost: 'दैनिक खर्च',
    monthlyCost: 'मासिक कुल',
    monthlyQuantity: 'मासिक कुल मात्रा',
    averageRate: 'औसत दर',
    autoCalculated: 'स्वतः परिकलित: मात्रा × दर = कुल',

    // Inventory
    inventorySection: 'घरेलू इन्वेंटरी (Stock & Supplies)',
    minStock: 'न्यूनतम स्टॉक (Min Alert)',
    purchasePrice: 'खरीद मूल्य',
    purchaseDate: 'खरीद तिथि',
    expiryDate: 'एक्सपायरी तिथि (वैकल्पिक)',
    location: 'रखने का स्थान',
    lowStockWarning: 'कम स्टॉक चेतावनी!',
    stockAdjust: 'स्टॉक घटाएं/बढ़ाएं',
    inStock: 'उपलब्ध स्टॉक',

    // Goals Module
    goalsSection: 'वित्तीय लक्ष्य (Goals Tracker)',
    targetAmount: 'लक्ष्य राशि (Target ₹)',
    startingAmount: 'शुरुआती राशि',
    targetDate: 'लक्ष्य पूर्ण करने की तिथि',
    progress: 'प्रगति (Progress)',
    timeRemaining: 'शेष समय',
    goalCompleted: 'लक्ष्य प्राप्त हुआ! बधाई!',

    // Budget Module
    budgetSection: 'मासिक बजट (Budgets)',
    monthlyBudget: 'पूरे महीने का कुल बजट',
    categoryBudget: 'श्रेणीवार बजट',
    spent: 'खर्च हुआ',
    remainingBudget: 'बचा हुआ बजट',
    overbudget: 'बजट से अधिक खर्च!',

    // Recurring Module
    recurringSection: 'आवर्ती भुगतान (Recurring)',
    frequency: 'आवृत्ति (Frequency)',
    nextDue: 'अगली देय तिथि',
    autoEntryLabel: 'ऐप खुलने पर स्वतः जोड़ें',
    daily: 'दैनिक (Daily)',
    weekly: 'साप्ताहिक (Weekly)',
    monthly: 'मासिक (Monthly)',
    quarterly: 'त्रैमासिक',
    yearly: 'वार्षिक (Yearly)',
    processDueNow: 'देय प्रविष्टियां प्रोसेस करें',

    // Reports Module
    reportsSection: 'वित्तीय रिपोर्ट और विश्लेषण',
    filterToday: 'आज',
    filterThisWeek: 'इस सप्ताह',
    filterThisMonth: 'इस महीने',
    filterPrevMonth: 'पिछला महीना',
    filterThisYear: 'इस वर्ष',
    filterCustom: 'कस्टम तारीख',
    exportPDF: 'प्रिंट / PDF रिपोर्ट',
    exportExcel: 'Excel / CSV निर्यात',
    categoryBreakdown: 'श्रेणीवार खर्च विश्लेषण',
    accountBreakdown: 'खातावार विश्लेषण',

    // Settings & Security
    backupSettings: 'बैकअप, सुरक्षा और सेटिंग्स',
    theme: 'थीम (Theme)',
    darkMode: 'डार्क मोड',
    lightMode: 'लाइट मोड',
    language: 'भाषा (Language)',
    passcodeLock: 'पासकोड लॉक (PIN)',
    enterPasscode: 'पासकोड दर्ज करें',
    enterToUnlock: 'अनलॉक करने के लिए अपना 4-अंकीय पिन दर्ज करें।',
    forgotPin: 'पिन भूल गए?',
    recoverPin: 'पिन रिकवर करें',
    securityQuestion: 'सुरक्षा प्रश्न',
    securityAnswer: 'सुरक्षा उत्तर',
    setNewPasscode: 'नया 4-अंकीय पिन सेट करें',
    removePasscode: 'पिन हटाएं',
    soundEffects: 'ध्वनि प्रभाव (Sound FX)',
    soundVolume: 'ध्वनि स्तर',
    jsonBackup: 'JSON बैकअप और रिस्टोर',
    backupDesc: 'डेटा बैकअप या रिस्टोर करने के लिए टेक्स्ट कॉपी/पेस्ट करें। 100% स्थानीय डेटा।',
    copyData: 'कॉपी करें',
    editData: 'एडिट करें',
    saveData: 'सेव करें',
    exportJSONFile: 'JSON फ़ाइल डाउनलोड',
    importJSONFile: 'JSON फ़ाइल अपलोड',
    dangerZone: 'खतरा क्षेत्र (Danger Zone)',
    clearAllData: 'सभी डेटा मिटाएं',
    confirmDelete: 'हाँ, मिटाएं',
    cancel: 'रद्द करें',
    save: 'सहेजें',
    close: 'बंद करें',
    edit: 'संपादित करें',
    delete: 'हटाएं',

    // Info Pages
    info_about_title: 'हमारे बारे में (About Us)',
    info_about_content:
      'युग फाइनेंस २.० (Yug Finance Manager 2.0) एक अत्यंत सुरक्षित, १००% ऑफलाइन व्यक्तिगत और पारिवारिक वित्त प्रबंधन उपकरण है। इसमें कोई सर्वर, लॉगिन या डेटा ट्रैकिंग नहीं है। आपका सारा डेटा केवल आपके डिवाइस पर स्थानीय रूप से संग्रहीत रहता है।',
    info_privacy_title: 'गोपनीयता नीति (Privacy Policy)',
    info_privacy_content:
      '१००% ऑफलाइन सुरक्षा: युग फाइनेंस कभी भी कोई वित्तीय डेटा किसी बाहरी सर्वर या क्लाउड पर नहीं भेजता। ऐप पूरी तरह से localStorage में काम करता है। हम नियमित रूप से JSON बैकअप फ़ाइल डाउनलोड करने की सलाह देते हैं।',
    info_disclaimer_title: 'अस्वीकरण (Disclaimer)',
    info_disclaimer_content:
      'युग फाइनेंस केवल व्यक्तिगत लेखा-जोखा और घरेलू व्यय ट्रैकिंग के लिए है। यह कोई विनियमित वित्तीय सलाह या बैंकिंग सेवा नहीं है।',
    info_terms_title: 'उपयोग की शर्तें (Terms of Use)',
    info_terms_content:
      'यह एप्लिकेशन "जैसा है" के आधार पर प्रदान किया गया है। उपयोगकर्ता अपने डेटा के बैकअप को सुरक्षित रखने के लिए स्वयं उत्तरदायी हैं।'
  },

  en: {
    // Navigation & App
    appName: 'Yug Finance 2.0',
    tagline: '100% Offline Personal & Household Finance Manager',
    dashboard: 'Dashboard',
    money: 'Money',
    household: 'Household',
    inventory: 'Inventory',
    goals: 'Goals',
    budget: 'Budget',
    recurring: 'Recurring',
    reports: 'Reports',
    more: 'More / Settings',
    settings: 'Settings',
    search: 'Global Search',

    // Info & Sidebar
    aboutUs: 'About Us',
    privacyPolicy: 'Privacy Policy',
    disclaimer: 'Disclaimer',
    termsOfUse: 'Terms of Use',
    contactSupport: 'Contact Support',
    quickActions: 'Quick Actions',
    modules: 'Module Toggles',

    // Dashboard Metrics
    netWorth: 'Total Net Worth',
    availableMoney: 'Available Money',
    previousBalance: 'Previous Bal.',
    startOfMonth: 'Start of Month',
    totalIncome: 'Total Income',
    thisMonth: 'This Month',
    totalExpense: 'Total Expense',
    monthlyNetChange: 'Monthly Net Change',
    netBalance: 'Net Balance',
    available: 'Available',
    savingsRate: 'Savings Rate',
    totalLend: 'Total Lent (Active)',
    remainingPrincipal: 'Remaining Principal',
    totalInvested: 'Total Invested (Net)',
    currentValue: 'Current Value',
    totalDebt: 'Total Borrowed / Debt',
    activeDebts: 'Active Liabilities',
    cashBalance: 'Cash Balance',
    bankBalance: 'Total Bank Balance',
    recentActivities: 'Recent Activities',
    noRecentActivities: 'No recent activities recorded.',
    checkAccountBalances: 'Check Account Balances',

    // Quick Add Buttons
    addIncome: '+ Add Income',
    addExpense: '- Add Expense',
    transfer: 'Transfer',
    addLend: 'Add Lend',
    addBorrow: 'Add Borrow',
    addInvestment: 'Add Investment',
    addGrocery: 'Add Grocery',
    addMilk: 'Add Milk',
    addWater: 'Add Water',
    addGoal: 'Add Goal',
    quickAdd: 'Universal Quick Add',

    // Money Module
    income: 'Income',
    expense: 'Expense',
    cash: 'Cash',
    bankAccounts: 'Bank Accounts',
    lend: 'Lend',
    borrow: 'Borrow / Debt',
    investments: 'Investments',
    transfers: 'Transfers',
    newTransaction: 'New Transaction',
    editTransaction: 'Edit Transaction',
    amount: 'Amount (₹)',
    date: 'Date',
    category: 'Category',
    account: 'Account',
    description: 'Description',
    note: 'Note / Comments',
    fromAccount: 'From Account',
    toAccount: 'To Account',
    saveTransaction: 'Save Transaction',

    // Bank Account Manager
    addAccount: 'Add Bank / Wallet Account',
    editAccount: 'Edit Account',
    accountName: 'Account Name',
    accountType: 'Account Type',
    openingBalance: 'Opening Balance (₹)',
    currentBalance: 'Current Balance',
    accountSavings: 'Savings Account',
    accountCurrent: 'Current Account',
    accountCash: 'Cash in Hand',
    accountWallet: 'Digital Wallet',
    accountOther: 'Other Account',
    saveAccount: 'Save Account',
    accountDeleted: 'Account removed',
    cannotDeleteAccountWithTx: 'Cannot delete an account with existing transactions!',

    // Lend Module
    lendSection: 'Lend Module (Giving Loans)',
    activeLoans: 'Active Loans',
    closedLoans: 'Closed Loans',
    noActiveLend: 'No active loans given.',
    noClosedLend: 'No closed loan entries.',
    personName: "Borrower's Name",
    amountGiven: 'Principal Amount (₹)',
    amountReceived: 'Total Received (₹)',
    remainingAmount: 'Remaining Amount',
    interestRate: 'Interest Rate (% p.a.)',
    emiTerm: 'EMI Term (Months)',
    returnDate: 'Due / Return Date',
    addRepayment: 'Add Repayment',
    addMoreLoan: 'Add More Principal',
    loanHistory: 'Repayment & History',
    markAsCompleted: 'Mark as Closed',
    markAsActive: 'Reopen Loan',

    // Borrow / Debt Module
    debtSection: 'Borrow / Debt Module (Liabilities)',
    activeDebtsList: 'Active Debts & Liabilities',
    closedDebtsList: 'Repaid Debts',
    noActiveDebt: 'No active debts recorded.',
    noClosedDebt: 'No repaid debt entries.',
    borrowFrom: 'Lender (Person / Institution)',
    amountBorrowed: 'Amount Borrowed (₹)',
    paidAmount: 'Repaid Amount (₹)',
    dueDate: 'Repayment Due Date',
    payDebt: 'Make Debt Repayment',
    debtRepayment: 'Debt Repayment Entry',

    // Investment Module
    investSection: 'Investment Portfolios',
    activePortfolios: 'Active Portfolios',
    closedPortfolios: 'Closed Portfolios',
    noActiveInvestments: 'No active investment portfolios.',
    portfolioName: 'Portfolio / Fund Name',
    investmentType: 'Investment Type',
    investedAmount: 'Total Invested',
    withdrawnAmount: 'Total Withdrawn',
    netInvested: 'Net Invested',
    withdrawAmount: 'Withdraw Amount',
    updateCurrentValue: 'Update Current Value (Manual)',
    manualValuationNotice: 'Market values are entered manually by you (100% offline).',

    // Household Module
    householdSection: 'Household Expense Manager',
    todayHousehold: "Today's Household Expense",
    monthlyHousehold: 'This Month Household Spending',
    grocery: 'Grocery',
    milk: 'Milk',
    water: 'Water',
    vegetables: 'Vegetables',
    fruits: 'Fruits',
    meat: 'Meat',
    fish: 'Fish',
    food: 'Food & Dining',
    fuel: 'Fuel & Petrol',
    medicine: 'Medicine & Health',
    bills: 'Bills & Utilities',
    shopping: 'Shopping',
    otherHousehold: 'Other Household',

    // Grocery & Milk & Water specific
    itemName: 'Item Name',
    quantity: 'Quantity',
    unit: 'Unit',
    ratePerUnit: 'Rate / Unit (₹)',
    shopVendor: 'Shop / Vendor Name',
    dailyCost: 'Daily Total',
    monthlyCost: 'Monthly Total',
    monthlyQuantity: 'Monthly Consumption',
    averageRate: 'Average Rate',
    autoCalculated: 'Auto-calculated: Qty × Rate = Total',

    // Inventory
    inventorySection: 'Household Inventory & Stock',
    minStock: 'Minimum Stock Alert',
    purchasePrice: 'Purchase Price',
    purchaseDate: 'Purchase Date',
    expiryDate: 'Expiry Date (Optional)',
    location: 'Storage Location',
    lowStockWarning: 'Low Stock Alert!',
    stockAdjust: 'Adjust Stock',
    inStock: 'Current Stock',

    // Goals Module
    goalsSection: 'Financial Goals Tracker',
    targetAmount: 'Target Amount (₹)',
    startingAmount: 'Starting Amount',
    targetDate: 'Target Completion Date',
    progress: 'Progress',
    timeRemaining: 'Time Remaining',
    goalCompleted: 'Goal Completed! Congratulations!',

    // Budget Module
    budgetSection: 'Budget Planner & Limits',
    monthlyBudget: 'Overall Monthly Budget',
    categoryBudget: 'Category Budgets',
    spent: 'Total Spent',
    remainingBudget: 'Remaining Budget',
    overbudget: 'Budget exceeded!',

    // Recurring Module
    recurringSection: 'Recurring Income & Expenses',
    frequency: 'Frequency',
    nextDue: 'Next Due Date',
    autoEntryLabel: 'Auto-entry on app launch',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    quarterly: 'Quarterly',
    yearly: 'Yearly',
    processDueNow: 'Process Due Items Now',

    // Reports Module
    reportsSection: 'Financial Reports & Analytics',
    filterToday: 'Today',
    filterThisWeek: 'This Week',
    filterThisMonth: 'This Month',
    filterPrevMonth: 'Previous Month',
    filterThisYear: 'This Year',
    filterCustom: 'Custom Range',
    exportPDF: 'Print / Save PDF Report',
    exportExcel: 'Export Excel / CSV',
    categoryBreakdown: 'Category Expense Analysis',
    accountBreakdown: 'Account Balance Breakdown',

    // Settings & Security
    backupSettings: 'Backup, Security & Settings',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    passcodeLock: 'Passcode PIN Lock',
    enterPasscode: 'Enter Passcode',
    enterToUnlock: 'Enter your 4-digit PIN to unlock.',
    forgotPin: 'Forgot PIN?',
    recoverPin: 'Recover PIN',
    securityQuestion: 'Security Question',
    securityAnswer: 'Security Answer',
    setNewPasscode: 'Set 4-Digit PIN',
    removePasscode: 'Remove PIN',
    soundEffects: 'Sound FX Engine',
    soundVolume: 'Sound Volume',
    jsonBackup: 'JSON Backup & Restore',
    backupDesc: 'Copy or paste raw data here to backup or restore. 100% private and offline.',
    copyData: 'Copy JSON',
    editData: 'Edit JSON',
    saveData: 'Save JSON',
    exportJSONFile: 'Download JSON File',
    importJSONFile: 'Upload JSON File',
    dangerZone: 'Danger Zone',
    clearAllData: 'Clear All Data',
    confirmDelete: 'Yes, Delete',
    cancel: 'Cancel',
    save: 'Save',
    close: 'Close',
    edit: 'Edit',
    delete: 'Delete',

    // Info Pages
    info_about_title: 'About Us',
    info_about_content:
      'Yug Finance Manager 2.0 is an offline-first personal and household finance manager built for uncompromising speed, privacy, and durability. It functions with zero servers, zero cookies, and zero external tracking. All data remains exclusively on your device.',
    info_privacy_title: 'Privacy Policy',
    info_privacy_content:
      '100% Offline Guarantee: Yug Finance never communicates with any external server or API. All financial records and settings reside solely in your browser local storage. We strongly recommend regular JSON file backups via Settings.',
    info_disclaimer_title: 'Disclaimer',
    info_disclaimer_content:
      'Yug Finance Manager is a personal bookkeeping and utility tool. It does not provide financial or tax advice. Calculations reflect data entered by the user.',
    info_terms_title: 'Terms of Use',
    info_terms_content:
      'This software is provided on an "as is" basis for personal, non-commercial use. Users are responsible for preserving and backing up their data.'
  }
};

export function getTranslation(lang: SupportedLanguage, key: string): string {
  const langDict = DICTIONARY[lang] || DICTIONARY['en'];
  return langDict[key] || DICTIONARY['en'][key] || key;
}
